package org.jitsi.jirecon;

public enum JireconEventId
{
    SESSION_ABORTED,
    SESSION_BUILDING,
    SESSION_RECEIVE_INIT,
    SESSION_CONSTRUCTED,
    
    RECORDER_INIT_OK,
    RECORDER_BUILDING,
    RECORDER_RECEIVING,
    RECORDER_RECORDING,
    RECORDER_ABORTED,
    
    TASK_ABORTED,
}
